# Copyright 2017 Sean Robertson

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{% if environ.get('TRAVIS', False) %}
  {% set version = environ.get('TRAVIS_BRANCH', '0.0') %}
  {% set build_num = environ['TRAVIS_BUILD_NUMBER'] %}
{% elif environ.get('APPVEYOR', False) %}
  {% set version = environ.get('APPVEYOR_REPO_TAG_NAME', '0.0') %}
  {% set build_num = environ['APPVEYOR_BUILD_NUMBER'] %}
{% else %}
  {% set version = environ.get('GIT_DESCRIBE_TAG', '0.0') %}
  {% set build_num = environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% endif %}
{% set version = version.replace('v','').replace('untagged', '0.0').split('-')[0] %}

package:
  name: pydrobert-kaldi
  version: {{ version }}

source:
  path: ..

requirements:
  host:
    - python
    - numpy 1.11.3                        # [ py < 39 ]
    - numpy 1.16.6                        # [ py >= 39 ]
    # FIXME(sdrobert): openblas-devel headers > 0.3.6 are messed up
    - openblas-devel 0.3.6                # [ blas_impl == 'openblas' ]
    - mkl-devel                           # [ blas_impl == 'mkl' ]
    - setuptools
    - setuptools_scm
    - swig 4.0.2
  build:
    - {{ compiler('cxx') }}
  run:
    # *-devel packages provide library packages as run_exports
    - python
    # there have been no major changes in the numpy api since 1.11.3 (currently
    # at 1.13). We'll see how long this lasts us
    - numpy >=1.11.3
    - future
    - six
    - enum34                              # [py2k]

build:
  number: {{ build_num }}
  detect_binary_files_with_prefix: False
  skip: True  # [blas_impl == 'openblas' and win]
  force_use_keys:
    - python

test:
  source_files:
    - tests
  requires:
    - pytest
    - nomkl                                # [ blas_impl != 'mkl' ]
  imports:
    - pydrobert
    - pydrobert.kaldi
  commands:
    - pytest -m "not pytorch"

about:
  home: https://github.com/sdrobert/pydrobert-kaldi
  license: Apache License 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Kaldi Swig bindings for Python
