version: build.{build}.branch.{branch}

environment:
  CIBW_TEST_REQUIRES: pytest
  CIBW_TEST_COMMAND: pytest {project}/tests -m "not pytorch"
  CIBW_BEFORE_BUILD: pip install -r {project}/recipe/cibw_before_requirements.txt
  CIBW_BEFORE_BUILD_LINUX: bash {project}/recipe/cibw_before_build_manylinux.sh
  CIBW_BEFORE_BUILD_MACOS: bash {project}/recipe/cibw_before_build_osx.sh
  CIBW_BEFORE_BUILD_WINDOWS: powershell.exe {project}/recipe/cibw_before_build_win.ps1
  CIBW_SKIP: pp*
  matrix:
    - job_name: win-cibw
      OPENBLASROOT: C:\Libraries\openblas
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    # - job_name: osx-cibw
    #   ACCELERATE: 1
    #   APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
    # - job_name: linux-cibw-x86_64
    #   CIBW_ARCHS_LINUX: x86_64
    #   OPENBLASROOT: /usr
    #   APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    # - job_name: linux-cibw-i686
    #   CIBW_ARCHS_LINUX: i686
    #   OPENBLASROOT: /usr
    #   APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu


stack: python 3.7

branches:
  except:
    - /docs/

init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }
  - sh: export DIST=dist-${APPVEYOR_JOB_NAME}
  - cmd: set DIST=dist-%APPVEYOR_JOB_NAME%
  - cmd: call C:\Miniconda37\Scripts\activate.bat

build: script

cache:
  - C:\Libraries\openblas # -> recipe\cibw_before_build_win.ps1

install:
  - python -m pip install cibuildwheel==2.3.1

build_script:
  - sh: cibuildwheel --output-dir ${DIST}
  - cmd: cibuildwheel --output-dir %DIST%

after_build:
  - cmd: 7z a %DIST%.zip %DIST%
  - sh: zip -r ${DIST}.zip ${DIST}

artifacts:
  path: '*.zip'
