version: build.{build}.branch.{branch}

environment:
  MINICONDA_LINUX_URL: "https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
  MINICONDA_OSX_URL: "https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh"
  CIBW_TEST_REQUIRES: pytest
  CIBW_TEST_COMMAND: pytest {project}/tests -m "not pytorch"
  CIBW_BEFORE_BUILD: pip install -r {project}/recipe/cibw_before_requirements.txt
  CIBW_BEFORE_BUILD_LINUX: bash {project}/recipe/cibw_before_build_manylinux.sh
  CIBW_BEFORE_BUILD_MACOS: bash {project}/recipe/cibw_before_build_osx.sh
  CIBW_BEFORE_BUILD_WINDOWS: powershell.exe {project}/recipe/cibw_before_build_win.ps1
  CIBW_SKIP: pp* cp27-* cp35-*
  matrix:
    - job_name: osx-cibw
      ACCELERATE: 1
      APPVEYOR_BUILD_WORKER_IMAGE: macos-mojave
    - job_name: win-cibw
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - job_name: linux-cibw-x86_64
      CIBW_ARCHS_LINUX: x86_64
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
    - job_name: linux-cibw-i686
      CIBW_ARCHS_LINUX: i686
      APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu


stack: python 3.8

branches:
  except:
    - /docs/

init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
      }
  - sh: export DIST=dist-${APPVEYOR_JOB_NAME}
  - cmd: set DIST=dist-%APPVEYOR_JOB_NAME%

build: script

install:
  - python -m pip install cibuildwheel==2.3.1

build_script:
  - sh: cibuildwheel --output-dir ${DIST}
  - cmd: cibuildwheel --output-dir %DIST%

after_build:
  - cmd: 7z a %DIST%.zip %DIST%
  - sh: zip -r ${DIST}.zip ${DIST}

artifacts:
  path: '*.zip'
